project:
  type: website

website:
  title: "<img src='/images/crick.jpeg' alt='' style='width: 2.6em; height: 2.2em; border-radius: 30%;'> <b>Cricket Winner Analyser</b>"
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO523-S24/project-final-DaakuDataSingh # Need to change to your project repo
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
